name: Synchronize Upstream
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -x
          git clone "https://github.com/${GITHUB_REPOSITORY}.git" .

          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          git remote add upstream "$UPSTREAM_REPO"
          git fetch upstream $UPSTREAM_BRANCH

          git checkout $LOCAL_BRANCH

          git rebase upstream/$UPSTREAM_BRANCH

          git status

          git remote set-url origin "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
          git push origin --force
        env:
          UPSTREAM_REPO: https://github.com/runtipi/runtipi-appstore.git
          UPSTREAM_BRANCH: master
          LOCAL_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
